//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfs.Custom.Software.Sgf.Web.Services {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.falkschool.com/webservices/", ConfigurationName="Sgf.Web.Services.CheckStubImportSoap")]
    public interface CheckStubImportSoap {
        
        // CODEGEN: Generating message contract since element name data from namespace http://www.falkschool.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.falkschool.com/webservices/ImportCheckStubs", ReplyAction="*")]
        Cfs.Custom.Software.Sgf.Web.Services.ImportCheckStubsResponse ImportCheckStubs(Cfs.Custom.Software.Sgf.Web.Services.ImportCheckStubsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportCheckStubsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportCheckStubs", Namespace="http://www.falkschool.com/webservices/", Order=0)]
        public Cfs.Custom.Software.Sgf.Web.Services.ImportCheckStubsRequestBody Body;
        
        public ImportCheckStubsRequest() {
        }
        
        public ImportCheckStubsRequest(Cfs.Custom.Software.Sgf.Web.Services.ImportCheckStubsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.falkschool.com/webservices/")]
    public partial class ImportCheckStubsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string data;
        
        public ImportCheckStubsRequestBody() {
        }
        
        public ImportCheckStubsRequestBody(string data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportCheckStubsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportCheckStubsResponse", Namespace="http://www.falkschool.com/webservices/", Order=0)]
        public Cfs.Custom.Software.Sgf.Web.Services.ImportCheckStubsResponseBody Body;
        
        public ImportCheckStubsResponse() {
        }
        
        public ImportCheckStubsResponse(Cfs.Custom.Software.Sgf.Web.Services.ImportCheckStubsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.falkschool.com/webservices/")]
    public partial class ImportCheckStubsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ImportCheckStubsResult;
        
        public ImportCheckStubsResponseBody() {
        }
        
        public ImportCheckStubsResponseBody(string ImportCheckStubsResult) {
            this.ImportCheckStubsResult = ImportCheckStubsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CheckStubImportSoapChannel : Cfs.Custom.Software.Sgf.Web.Services.CheckStubImportSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckStubImportSoapClient : System.ServiceModel.ClientBase<Cfs.Custom.Software.Sgf.Web.Services.CheckStubImportSoap>, Cfs.Custom.Software.Sgf.Web.Services.CheckStubImportSoap {
        
        public CheckStubImportSoapClient() {
        }
        
        public CheckStubImportSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CheckStubImportSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckStubImportSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckStubImportSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cfs.Custom.Software.Sgf.Web.Services.ImportCheckStubsResponse Cfs.Custom.Software.Sgf.Web.Services.CheckStubImportSoap.ImportCheckStubs(Cfs.Custom.Software.Sgf.Web.Services.ImportCheckStubsRequest request) {
            return base.Channel.ImportCheckStubs(request);
        }
        
        public string ImportCheckStubs(string data) {
            Cfs.Custom.Software.Sgf.Web.Services.ImportCheckStubsRequest inValue = new Cfs.Custom.Software.Sgf.Web.Services.ImportCheckStubsRequest();
            inValue.Body = new Cfs.Custom.Software.Sgf.Web.Services.ImportCheckStubsRequestBody();
            inValue.Body.data = data;
            Cfs.Custom.Software.Sgf.Web.Services.ImportCheckStubsResponse retVal = ((Cfs.Custom.Software.Sgf.Web.Services.CheckStubImportSoap)(this)).ImportCheckStubs(inValue);
            return retVal.Body.ImportCheckStubsResult;
        }
    }
}
